# Form implementation generated from reading ui file 'UI/mainui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form.resize(800, 800)
        Form.setMaximumSize(QtCore.QSize(800, 800))
        self.notegroup = QtWidgets.QGroupBox(parent=Form)
        self.notegroup.setGeometry(QtCore.QRect(20, 560, 600, 200))
        self.notegroup.setMaximumSize(QtCore.QSize(600, 200))
        self.notegroup.setTitle("")
        self.notegroup.setObjectName("notegroup")
        self.Notelable = QtWidgets.QLabel(parent=self.notegroup)
        self.Notelable.setGeometry(QtCore.QRect(50, 20, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Notelable.setFont(font)
        self.Notelable.setObjectName("Notelable")
        self.Notext = QtWidgets.QTextBrowser(parent=self.notegroup)
        self.Notext.setGeometry(QtCore.QRect(50, 40, 500, 140))
        self.Notext.setMaximumSize(QtCore.QSize(500, 200))
        self.Notext.setObjectName("Notext")
        self.Cameragroup = QtWidgets.QGroupBox(parent=Form)
        self.Cameragroup.setGeometry(QtCore.QRect(60, 20, 680, 520))
        self.Cameragroup.setMaximumSize(QtCore.QSize(680, 520))
        self.Cameragroup.setTitle("")
        self.Cameragroup.setObjectName("Cameragroup")
        # --- PHẦN CHỈNH SỬA ĐỂ CĂN GIỮA ---
        # 1. Tạo một Layout cho Cameragroup
        self.camera_layout = QtWidgets.QVBoxLayout(self.Cameragroup)

        # 2. Tạo QLabel để hiển thị Video (thay vì self.label cũ)
        self.video_label = QtWidgets.QLabel(parent=self.Cameragroup)
        self.video_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)  # Căn giữa nội dung
        self.video_label.setText("Camera chưa chạy")

        # Cấu hình font cho thông báo ban đầu
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.video_label.setFont(font)

        # 3. Thêm video_label vào layout
        self.camera_layout.addWidget(self.video_label)
        self.Buttongroup = QtWidgets.QGroupBox(parent=Form)
        self.Buttongroup.setGeometry(QtCore.QRect(640, 560, 140, 200))
        self.Buttongroup.setMaximumSize(QtCore.QSize(140, 200))
        self.Buttongroup.setTitle("")
        self.Buttongroup.setObjectName("Buttongroup")
        self.startbutton = QtWidgets.QPushButton(parent=self.Buttongroup)
        self.startbutton.setGeometry(QtCore.QRect(20, 40, 100, 40))
        self.startbutton.setMaximumSize(QtCore.QSize(100, 40))
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtWidgets.QPushButton(parent=self.Buttongroup)
        self.stopbutton.setGeometry(QtCore.QRect(20, 120, 100, 40))
        self.stopbutton.setObjectName("stopbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Face Recognation"))
        self.Notelable.setText(_translate("Form", "Notification"))
        self.video_label.setText(_translate("Form", "Camera chưa chạy"))
        self.startbutton.setText(_translate("Form", "START"))
        self.stopbutton.setText(_translate("Form", "STOP"))
