# Form implementation generated from reading ui file 'UI/mainui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form.resize(1280, 720)
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        self.notegroup = QtWidgets.QGroupBox(parent=Form)
        self.notegroup.setGeometry(QtCore.QRect(780, 200, 480, 500))
        self.notegroup.setMaximumSize(QtCore.QSize(480, 500))
        self.notegroup.setTitle("")
        self.notegroup.setObjectName("notegroup")
        self.Notelable = QtWidgets.QLabel(parent=self.notegroup)
        self.Notelable.setGeometry(QtCore.QRect(20, 20, 200, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Notelable.setFont(font)
        self.Notelable.setStyleSheet("QLabel{\n"
"font-size:15;\n"
"font-weight:bold;\n"
"}")
        self.Notelable.setObjectName("Notelable")
        self.Notext = QtWidgets.QTextBrowser(parent=self.notegroup)
        self.Notext.setGeometry(QtCore.QRect(20, 45, 440, 435))
        self.Notext.setMaximumSize(QtCore.QSize(500, 1000))
        self.Notext.setObjectName("Notext")
        self.Cameragroup = QtWidgets.QGroupBox(parent=Form)
        self.Cameragroup.setGeometry(QtCore.QRect(20, 200, 740, 500))
        self.Cameragroup.setMaximumSize(QtCore.QSize(740, 500))
        self.Cameragroup.setTitle("")
        self.Cameragroup.setObjectName("Cameragroup")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.Cameragroup)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.camera_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.camera_layout.setContentsMargins(0, 0, 0, 0)
        self.camera_layout.setSpacing(0)
        self.camera_layout.setObjectName("camera_layout")
        self.video_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.video_label.setFont(font)
        self.video_label.setStyleSheet("QLabel{\n"
"font-weight:bold;\n"
"font-size:16\n"
"}")
        self.video_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.video_label.setObjectName("video_label")
        self.camera_layout.addWidget(self.video_label)
        self.ControllGroup = QtWidgets.QGroupBox(parent=Form)
        self.ControllGroup.setGeometry(QtCore.QRect(780, 20, 230, 160))
        self.ControllGroup.setMaximumSize(QtCore.QSize(1000, 160))
        self.ControllGroup.setTitle("")
        self.ControllGroup.setObjectName("ControllGroup")
        self.startbutton = QtWidgets.QPushButton(parent=self.ControllGroup)
        self.startbutton.setGeometry(QtCore.QRect(20, 20, 190, 50))
        self.startbutton.setMaximumSize(QtCore.QSize(190, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.startbutton.setFont(font)
        self.startbutton.setStyleSheet("QPushButton{\n"
"border:2px solid #8f8f91;\n"
"border-radius: 5px;\n"
"font-weight:bold;\n"
"font-size:15\n"
"}")
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtWidgets.QPushButton(parent=self.ControllGroup)
        self.stopbutton.setGeometry(QtCore.QRect(20, 90, 190, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.stopbutton.setFont(font)
        self.stopbutton.setStyleSheet("QPushButton{\n"
"border:2px solid #8f8f91;\n"
"border-radius: 5px;\n"
"font-weight:bold;\n"
"font-size:15\n"
"}")
        self.stopbutton.setObjectName("stopbutton")
        self.ProcessBarGroup = QtWidgets.QGroupBox(parent=Form)
        self.ProcessBarGroup.setGeometry(QtCore.QRect(20, 20, 740, 121))
        self.ProcessBarGroup.setTitle("")
        self.ProcessBarGroup.setObjectName("ProcessBarGroup")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.ProcessBarGroup)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 741, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.process_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.process_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.process_layout.setContentsMargins(0, 0, 0, 0)
        self.process_layout.setSpacing(0)
        self.process_layout.setObjectName("process_layout")
        self.OpenCam = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.OpenCam.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OpenCam.setFont(font)
        self.OpenCam.setStyleSheet("QLabel {\n"
"    background-color: #d1d1d1; /* Màu xám */\n"
"    border: 2px solid #a1a1a1;\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    color: #555555;\n"
"    font-weight: bold;\n"
"}")
        self.OpenCam.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.OpenCam.setWordWrap(True)
        self.OpenCam.setObjectName("OpenCam")
        self.process_layout.addWidget(self.OpenCam)
        self.arrow1 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.arrow1.setMaximumSize(QtCore.QSize(40, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.arrow1.setFont(font)
        self.arrow1.setObjectName("arrow1")
        self.process_layout.addWidget(self.arrow1)
        self.Detect = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Detect.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Detect.setFont(font)
        self.Detect.setStyleSheet("QLabel {\n"
"    background-color: #d1d1d1; /* Màu xám */\n"
"    border: 2px solid #a1a1a1;\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    color: #555555;\n"
"    font-weight: bold;\n"
"}")
        self.Detect.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Detect.setWordWrap(True)
        self.Detect.setObjectName("Detect")
        self.process_layout.addWidget(self.Detect)
        self.arrow2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.arrow2.setMaximumSize(QtCore.QSize(40, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.arrow2.setFont(font)
        self.arrow2.setObjectName("arrow2")
        self.process_layout.addWidget(self.arrow2)
        self.Embedding = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Embedding.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Embedding.setFont(font)
        self.Embedding.setStyleSheet("QLabel {\n"
"    background-color: #d1d1d1; /* Màu xám */\n"
"    border: 2px solid #a1a1a1;\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    color: #555555;\n"
"    font-weight: bold;\n"
"}")
        self.Embedding.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Embedding.setWordWrap(True)
        self.Embedding.setObjectName("Embedding")
        self.process_layout.addWidget(self.Embedding)
        self.arrow3 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.arrow3.setMaximumSize(QtCore.QSize(40, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.arrow3.setFont(font)
        self.arrow3.setObjectName("arrow3")
        self.process_layout.addWidget(self.arrow3)
        self.Query = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Query.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Query.setFont(font)
        self.Query.setStyleSheet("QLabel {\n"
"    background-color: #d1d1d1; /* Màu xám */\n"
"    border: 2px solid #a1a1a1;\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    color: #555555;\n"
"    font-weight: bold;\n"
"}")
        self.Query.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Query.setWordWrap(True)
        self.Query.setObjectName("Query")
        self.process_layout.addWidget(self.Query)
        self.arrow4 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.arrow4.setMaximumSize(QtCore.QSize(40, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.arrow4.setFont(font)
        self.arrow4.setObjectName("arrow4")
        self.process_layout.addWidget(self.arrow4)
        self.Draw = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.Draw.setMaximumSize(QtCore.QSize(100, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Draw.setFont(font)
        self.Draw.setStyleSheet("QLabel {\n"
"    background-color: #d1d1d1; /* Màu xám */\n"
"    border: 2px solid #a1a1a1;\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    color: #555555;\n"
"    font-weight: bold;\n"
"}")
        self.Draw.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Draw.setWordWrap(True)
        self.Draw.setObjectName("Draw")
        self.process_layout.addWidget(self.Draw)
        self.Mainprocesslabel = QtWidgets.QLabel(parent=self.ProcessBarGroup)
        self.Mainprocesslabel.setGeometry(QtCore.QRect(0, 0, 741, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Mainprocesslabel.setFont(font)
        self.Mainprocesslabel.setStyleSheet("QLabel {\n"
"    background-color: #2ecc71; /* Màu xám */\n"
"    border: 2px solid #a1a1a1;\n"
"    border-radius: 5px; /* Bo góc nhẹ */\n"
"    color: #555555;\n"
"    font-weight: bold;\n"
"}")
        self.Mainprocesslabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Mainprocesslabel.setObjectName("Mainprocesslabel")
        self.SelectGroup = QtWidgets.QGroupBox(parent=Form)
        self.SelectGroup.setGeometry(QtCore.QRect(1030, 20, 230, 160))
        self.SelectGroup.setTitle("")
        self.SelectGroup.setObjectName("SelectGroup")
        self.radio2 = QtWidgets.QRadioButton(parent=self.SelectGroup)
        self.radio2.setGeometry(QtCore.QRect(20, 90, 190, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radio2.setFont(font)
        self.radio2.setObjectName("radio2")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radio2)
        self.radio1 = QtWidgets.QRadioButton(parent=self.SelectGroup)
        self.radio1.setGeometry(QtCore.QRect(20, 20, 190, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radio1.setFont(font)
        self.radio1.setChecked(True)
        self.radio1.setObjectName("radio1")
        self.buttonGroup.addButton(self.radio1)
        self.InButton = QtWidgets.QPushButton(parent=Form)
        self.InButton.setGeometry(QtCore.QRect(20, 145, 360, 50))
        self.InButton.setStyleSheet("QPushButton{\n"
"border: 2px solid #8f8f91;\n"
"border-radius: 10px;\n"
"background-color: #3498db;\n"
"color: white;\n"
"font-size: 15;\n"
"font-weight: bold\n"
"}\n"
"")
        self.InButton.setObjectName("InButton")
        self.OutButton = QtWidgets.QPushButton(parent=Form)
        self.OutButton.setGeometry(QtCore.QRect(400, 145, 360, 50))
        self.OutButton.setStyleSheet("QPushButton{\n"
"border: 2px solid #8f8f91;\n"
"border-radius: 10px;\n"
"font-size: 15;\n"
"font-weight: bold\n"
"}\n"
"")
        self.OutButton.setObjectName("OutButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Face Recognation"))
        self.Notelable.setText(_translate("Form", "Notification"))
        self.video_label.setText(_translate("Form", "Camera chưa chạy"))
        self.startbutton.setText(_translate("Form", "START"))
        self.stopbutton.setText(_translate("Form", "STOP"))
        self.OpenCam.setText(_translate("Form", "GET IMAGE"))
        self.arrow1.setText(_translate("Form", "→"))
        self.Detect.setText(_translate("Form", "DETECT"))
        self.arrow2.setText(_translate("Form", "→"))
        self.Embedding.setText(_translate("Form", "EMBEDDING"))
        self.arrow3.setText(_translate("Form", "→"))
        self.Query.setText(_translate("Form", "QUERY DATABASE"))
        self.arrow4.setText(_translate("Form", "→"))
        self.Draw.setText(_translate("Form", "DRAW RESULT"))
        self.Mainprocesslabel.setText(_translate("Form", "Main Process"))
        self.radio2.setText(_translate("Form", "real-time"))
        self.radio1.setText(_translate("Form", "step by step"))
        self.InButton.setText(_translate("Form", "IN MODE"))
        self.OutButton.setText(_translate("Form", "OUT MODE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
